{
 "title": "Solar Logger",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Logger Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" },
    {
     "expr": "abs(idelta(solarlogger_error_total[$__range]))",
     "legendFormat": "Fehler"
    }
   ]
  },
  {
   "title": "Geräte Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_status{address=\"05\"}",
     "legendFormat": "WR 1 ({{type}})"
    },
    {
     "expr": "solarlogger_status{address=\"02\"}",
     "legendFormat": "WR 2 ({{type}})"
    },
    {
     "expr": "solarlogger_status{address=\"03\"}",
     "legendFormat": "WR 3 ({{type}})"
    },
    {
     "expr": "solarlogger_status{address=\"04\"}",
     "legendFormat": "WR 4 ({{type}})"
    },
    {
     "expr": "solarlogger_status{address=\"01\"}",
     "legendFormat": "Powador Protect"
    }
   ]
  },
  {
   "title": "Leistungsverlauf [Watt]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg_over_time(solarlogger_total_ac_power[15m])",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Aktuelle Leistung [Watt]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_total_dc_power{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_total_dc_power{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_total_dc_power{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_total_dc_power{address=\"04\"}",
     "legendFormat": "WR 4"
    },
    {
     "expr": "sum(solarlogger_total_dc_power)",
     "legendFormat": "Summe"
    }
   ]
  },
  {
   "title": "Ertragsverlauf [Wh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "solarlogger_daily_yield{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"04\"}",
     "legendFormat": "WR 4"
    }
   ]
  },
  {
   "title": "Tagesertrag (Wh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_daily_yield{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"04\"}",
     "legendFormat": "WR 4"
    },
    { "expr": "sum(solarlogger_daily_yield)", "legendFormat": "Summe" }
   ]
  },
  {
   "title": "Ertragsverlauf [Wh]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "solarlogger_daily_yield{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"04\"}",
     "legendFormat": "WR 4"
    }
   ]
  },
  {
   "title": "Tagesertrag (Wh)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_daily_yield{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_daily_yield{address=\"04\"}",
     "legendFormat": "WR 4"
    },
    { "expr": "sum(solarlogger_daily_yield)", "legendFormat": "Summe" }
   ]
  },
  {
   "title": "Board-Temparatur",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "solarlogger_board_temperature_celsius{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_board_temperature_celsius{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_board_temperature_celsius{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_board_temperature_celsius{address=\"04\"}",
     "legendFormat": "WR 4"
    }
   ]
  },
  {
   "title": "Betriebszeit heute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum by (address) (\n        count_over_time(\n            (solarlogger_total_ac_power > 0)[$__range:1m]\n        )\n    )\n)",
     "legendFormat": "{{address}}"
    },
    {
     "expr": "sum(\n    sum by (address) (\n        count_over_time(\n            (solarlogger_total_ac_power > 0)[$__range:1m]\n        )\n    )\n)",
     "legendFormat": "Summe"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "timeseries",
   "description": "Zeitdauer der Anfragen an die Wechselrichter ",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(solarlogger_serial_port_speed_seconds)/5",
     "legendFormat": "Avg Query Time"
    }
   ]
  },
  {
   "title": "Gesamtertrag",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_accumulated_yield{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_accumulated_yield{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_accumulated_yield{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_accumulated_yield{address=\"04\"}",
     "legendFormat": "WR 4"
    },
    {
     "expr": "sum(solarlogger_accumulated_yield)",
     "legendFormat": "Summe"
    }
   ]
  },
  {
   "title": "Serial Port Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(solarlogger_serial_port_event_total{event!=\"start\"}[$__rate_interval])",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Gesamt Betriebszeit",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solarlogger_accumulated_yield_hours{address=\"05\"}",
     "legendFormat": "WR 1"
    },
    {
     "expr": "solarlogger_accumulated_yield_hours{address=\"02\"}",
     "legendFormat": "WR 2"
    },
    {
     "expr": "solarlogger_accumulated_yield_hours{address=\"03\"}",
     "legendFormat": "WR 3"
    },
    {
     "expr": "solarlogger_accumulated_yield_hours{address=\"04\"}",
     "legendFormat": "WR 4"
    },
    {
     "expr": "sum(solarlogger_accumulated_yield_hours)",
     "legendFormat": "Summe"
    }
   ]
  },
  {
   "title": "Cos phi",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "min without (nature)(solarlogger_cos_phi) > 0.9",
     "legendFormat": "{{address}}"
    }
   ]
  }
 ]
}